language: node_js
node_js:
  - "8.9"

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sed -i "s/http:\/\/registry.npm.taobao.org/https:\/\/registry.npmjs.org/g" yarn.lock

install:
  - yarn

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
