language: node_js
node_js:
  - "10"

branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

before_script:
  - sed -i 's/root:\ \//root:\ \/leetcode\//' _config.yml
  - sed -i "s/http:\/\/registry.npm.taobao.org/https:\/\/registry.npmjs.org/g" yarn.lock

script:
  - hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
